# -*- coding: utf-8 -*-
"""CustomModel_YOLOv5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHrzMuuDlKeSzyJKYKhEJy2gX1enZyxa

# **Install Requirements**
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

"""## **Data lebelling and image augmentation**"""

# set up environment
os.environ["DATASET_DIRECTORY"] = "/content/datasets"

#after following the link above, recieve python code with these fields filled in
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="WM0SHgENXlEsvRIv27gH")
project = rf.workspace("a-hoqep").project("checkcolorshirt-mark2")
dataset = project.version(11).download("yolov5")

"""# **Train custom model with YOLOv5**"""

!python train.py --img 460 --batch 32 --epochs 200 --data {dataset.location}/data.yaml --weights yolov5m.pt --cache

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q wandb
import wandb
wandb.login()

"""# **Detect objects in an image using custom model**"""

!python detect.py --weights runs/train/exp/weights/best.pt --img 640 --conf 0.4 --source {dataset.location}/test/images

"""# **Display result image**"""

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/detect/exp1/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")